### ISSUE TITLE
Handling of native token in both chain such as USDC

### ISSUE THREAD

**Issue by 524119574** [certusone/wormhole#186]
Tokens such as USDC is native to both Solana and Ethereum. I am wondering how does worm hole handles this kind of tokens. Thanks!

**Comment by hendrikhofstadt** [comment]
Unfortunately there’s no way we can build a mapping between native and wrapped token.

So you’ll have a wrapped USDC and a native USDC on both chains.

it’s up to the token minter to decide whether to allow conversion of wrapped and native assets into each other (but I doubt this will happen for stable coins because it would make it hard to track supply). In the case of such centralised stable coins I’d wait for the each asset to offer a native bridge.
