### ISSUE TITLE
postVAA confirmation on Solana times out on mainnet

### ISSUE THREAD

**Issue by wormat** [certusone/wormhole#574]
The default timeout for `SolanaConnection.confirmTransaction` is 30s for the default commitment level. Because of this we're experiencing timeouts a lot on mainnet. What we're doing elsewhere in our application is wrapping the method with a number of retries, similar to what you're doing with `getSignedVAAWithRetry`. It would be great if you could do the same in `postVAA` and/or provide some customization (eg with commitment level `max` the timeout is 60s which we might be less likely to reach).

**Comment by evan-gray** [comment]
Thanks for the feedback! I’ve long wanted to rework postVAA to give back the list of instructions to be signed at the leisure of the application (because if one in the middle fails the whole thing has to start over with the current SDK design, which is suboptimal). Would this approach of handing back the instructions, like the other functions do, match up with what you’re asking for?

**Comment by wormat** [comment]
That would be great for us, and I think a much nicer design for the SDK.

**Comment by evan-gray** [comment]
Awesome, will try to get it in this week!

**Comment by evan-gray** [comment]
should be doable with https://www.npmjs.com/package/@certusone/wormhole-sdk/v/0.1.5
note from the changelog 🙂 
```
deprecated postVaaSolana added postVaaSolanaWithRetry, which will retry transactions which failed during processing. added createVerifySignaturesInstructions, createPostVaaInstruction, which allows users to construct the postVaa process for themselves at the instruction level. added chunks and sendAndConfirmTransactionsWithRetry as utility functions.
```
