### ISSUE TITLE
terra: async VAA submission

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#95]
The Terra VAA submission currently blocks the observation loop.

This needs to be refactored to submit asynchronously like Solana to avoid stalls when the terra request takes longer than expected.

https://github.com/certusone/wormhole/blob/f072e8c36af5619611292c3bd4cbe936a2c69612/bridge/pkg/processor/observation.go#L203

**Comment by ysavchenko** [comment]
There is a suspiciously simple solution to this, use go routine to submit VAA to Terra, just changing the line https://github.com/certusone/wormhole/blob/5997f133c3df8cd1b13b015977b60a0a9b6efad0/bridge/pkg/processor/observation.go#L163 
to
`go p.terraVAASubmission(ctx, signed, hash)`
Since nothing depends on the success of sending VAA to Terra (except for logging the error) it could be that easy. @leoluk what do you think?

**Comment by leoluk** [comment]
Sounds too good to be true :) But I agree, a goroutine is fine here since we don't need to control concurrency.
