### ISSUE TITLE
terra: read terra fee payer secret from file like all other keys

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#96]
Using TERRA_FEE_PAYER is inconsistent with p2p, Solana and bridge keys.

**Comment by ysavchenko** [comment]
I've checked the current code as as far as I see Ethereum transactions are signed only in devnet mode by deterministic keys and Solana transactions are signed by the agent (id.json file there). Both do not work for Terra, because we need transactions signed not only in devnet mode and signing happens not on the Terra node, but in the bridge itself.

So what is the best way to proceed here @leoluk ? Or may be I've missed some other file-based key management in the bridge?

**Comment by leoluk** [comment]
Just change it to read the key from a file vs. reading it from an environment variable.
